[[pages]]
name = "Home"
icon = "🏠"
is_section = true

[[pages]]
path = "pages/1_🤖_text_to_sql_client.py"
name = "Insight to Data"
icon = "🤖"


[[pages]]
path = "pages/2_📈_text_to_sql_metrics.py"
name = "Metrics"
icon = "📈"